name: "order book visualization"
services:
  frontend:
    image: "frontend:latest"
    build:
    ports:
      - "8080:8080"
    environment:
      - "HUB_URL=http://backend/orderbookhub:8081"
    depends_on:
      - backend
  
  backend:
    image: "backend:latest"
    ports:
      - "8081:8081"
    environment:
      - "BITSTAMP_SOCKET=wss://ws.bitstamp.net"
    depends_on:
      - db

  db:
    image: postgres:17.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: house_tarification
    ports:
      - "5432:5432"
    networks:
      - "order-book-visualization"
      

networks:
  default:
    name: "order-book-visualization"
  