name: "order book visualization"
services:
  frontend:
    build: ./OrderBook.Web
    ports:
      - "8080:5268"
    environment:
      - "HUB_URL=http://backend/orderbookhub:8081"
    networks:
      - "order-book-visualization"
    depends_on:
      - backend
  
  backend:
    build: ./OrderBook.Api
    ports:
      - "8081:5192"
    environment:
      - "BITSTAMP_SOCKET=wss://ws.bitstamp.net"
    networks:
      - "order-book-visualization"    

networks:
  default:
    name: "order-book-visualization"
  