FROM mcr.microsoft.com/dotnet/aspnet:9.0.0-bookworm-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 5268
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0.101-bookworm-slim AS build
WORKDIR /scr
COPY ["OrderBook.Web/.", "OrderBook.Web/."]
COPY ["OrderBook.Shared/.", "OrderBook.Shared/."]  

RUN dotnet restore "OrderBook.Web/OrderBook.Web.csproj"

WORKDIR "/scr/OrderBook.Web"

RUN dotnet build "OrderBook.Web.csproj" -o /app/build

FROM build AS publish
RUN dotnet publish "OrderBook.Web.csproj" -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OrderBook.Web.dll"]